[package]
name = "rustbuster"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.15", features = ["full"] }
colored = "2.0"
terminal_size = "0.2"
