[package]
name = "rustbuster"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
colored = "2.0"
reqwest = { version = "0.11", features = ["blocking"] }
rayon = "1.8"
indicatif = "0.17"
